name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.2.0
          java: java16

      - run: |
          cd ..
          git clone https://github.com/jreleaser/jreleaser.git
          cd jreleaser
          ./gradlew publishToMavenLocal
          cd ..
          cd api

      - run: |
          chmod +x gradlew
          ./gradlew build
