name: publish

on:
  pull_request:
    types: [ closed ]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: whelk-io/maven-settings-xml-action@v12
        with:
          servers: '[{ "id": "shiruka", "username": "${{ secrets.SHIRUKA_USERNAME }}", "password": "${{ secrets.SHIRUKA_PASSWORD }}"}]'

      - uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: mvn clean deploy -Pshiruka -ntp -B
